### ISSUE TITLE
How to measure the inactive memory of a process without your kernel？

### ISSUE THREAD

**Issue by miraclejzd** [BarrinXu/FaaSMem#3]
I have read your paper of  ASPLOS 24', which I really think is master-piece. I am wondering how to measure the active and inactive memory pages of a process. Can you please provide the metrics and how to get them?

**Comment by BarrinXu** [comment]
We rely on the Linux kernel's MGLRU feature to measure the active and inactive pages. 
You can enable MGLRU in your kernel (A recent kernel version is required (Linux 6.1+), and you may need to re-compile).
Build the kernel with the following configurations.
CONFIG_LRU_GEN=y
CONFIG_LRU_GEN_ENABLED=y

Specifically, MGLRU segregates the pages into different time barriers. 
In [https://github.com/BarrinXu/FaaSMem/blob/main/FaaSMem-core/src/function_manager/MGLRU.py#L69](https://github.com/BarrinXu/FaaSMem/blob/main/FaaSMem-core/src/function_manager/MGLRU.py#L69), we add a new time barrier. 
In [https://github.com/BarrinXu/FaaSMem/blob/main/FaaSMem-core/src/function_manager/MGLRU.py#L28](https://github.com/BarrinXu/FaaSMem/blob/main/FaaSMem-core/src/function_manager/MGLRU.py#L28)  ,we collect the pages between different barriers. 
In [https://github.com/BarrinXu/FaaSMem/blob/main/FaaSMem-core/src/function_manager/MGLRU.py#L50](https://github.com/BarrinXu/FaaSMem/blob/main/FaaSMem-core/src/function_manager/MGLRU.py#L50), we offload the pages before a certain barrier.
You can also refer to the MGLRU guide for more details. See [measure pages via MGLRU](https://docs.kernel.org/admin-guide/mm/multigen_lru.html#working-set-estimation), and [reclaim pages via MGLRU](https://docs.kernel.org/admin-guide/mm/multigen_lru.html#proactive-reclaim).

**Comment by miraclejzd** [comment]
Gotcha, thank you for your detailed explanation. The guide seems great, I will get through it at once.
